### ISSUE TITLE
Is this repo accepting PRs?

### ISSUE THREAD

**Issue by KontrolG** [etaiklein/FormattedMessage#1]
I want to add a new functionally to this extension, is it open to PRs?

**Comment by etaiklein** [comment]
What do you have in mind?

**Comment by KontrolG** [comment]
Thanks for your answer.

I'm currently using this extension in one proyect that uses the `formatjs/enforce-id` rule for ESLint with the `[sha512:contenthash:base64:6]` pattern, so I was wondering if I can try to add some customization to the extension to change the current id pattern.
That way I will only need the extension without the ESLint rule.

**Comment by KontrolG** [comment]
BTW, thanks for the extension, it is the only one that have worked for me 😊

**Comment by etaiklein** [comment]
I'm glad you've found this extension useful.

If you make the alternate id style an optional setting configuration, then I don't see why not.
