### ISSUE TITLE
Allow to customize the current id generation pattern

### ISSUE THREAD

**Issue by KontrolG** [etaiklein/FormattedMessage#2]
I'm currently using this extension in one proyect that uses the formatjs/enforce-id rule for ESLint with the [sha512:contenthash:base64:6] pattern, so when I add a <FormattedMessage /> this automatically throws an ESLint error due to ID incompatibility.

Some customization to the extension to change the current id pattern would help to prevents those errors.

**Comment by KontrolG** [comment]
@etaiklein I already have a branch with the changes needed for this, but I can't push it 😢 there is some chance that you change te repo to a public one?

**Comment by etaiklein** [comment]
Nice one! Ill test it out on monday. Can you also update the README to describe the new options?
